/** @format */
// Authentication types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_AUTH_LOGIN_ERROR = 'SET_AUTH_LOGIN_ERROR';
export const SET_AUTH_REGISTER_ERROR = 'SET_AUTH_REGISTER_ERROR';
export const UI_LOADING_LOGIN_BUTTON = 'UI_LOADING_LOGIN_BUTTON';
export const UI_LOADING_REGISTER_BUTTON = 'UI_LOADING_REGISTER_BUTTON';
export const UI_LOADING_LOGOUT_BUTTON = 'UI_LOADING_LOGOUT_BUTTON';
export const SHOW_AUTH_TOAST = 'SHOW_AUTH_TOAST';
export const SHOW_AUTH_TOAST_REGISTER = 'SHOW_AUTH_TOAST_REGISTER';
// UI_LOADING,

// artworkAction types
export const GET_ARTWORK = 'GET_ARTWORK';
export const UI_LOADING_ARTWORK = 'UI_LOADING_ARTWORK';
export const GET_ARTWORKS = 'GET_ARTWORKS';
export const UI_LOADING_ARTWORKS = 'UI_LOADING_ARTWORKS';
