/** @format */
// Authentication types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_AUTH_LOGIN_ERROR = "SET_AUTH_LOGIN_ERROR";
export const SET_AUTH_REGISTER_ERROR = "SET_AUTH_REGISTER_ERROR";
export const UI_LOADING_LOGIN_BUTTON = "UI_LOADING_LOGIN_BUTTON";
export const UI_LOADING_REGISTER_BUTTON = "UI_LOADING_REGISTER_BUTTON";
export const UI_LOADING_LOGOUT_BUTTON = "UI_LOADING_LOGOUT_BUTTON";
// UI_LOADING,
